### ISSUE TITLE
Loading Stuck Crash (Arch Linux)

### ISSUE THREAD

**Issue by Grimmoire** [butterproject/butter-desktop#281]
When I click "Loading stuck, click here it crashes without a dump file. Here's the whole log

```
Running "exec:linux64"` (exec) task
>> [28749:0216/020458:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
>> [28794:0216/020502:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
>> [28749:0216/020503:INFO:CONSOLE(6)] ""Database path: /home/grimmoire/.config/Butter"", source: app://host/src/app/database.js (6)
>> [28749:0216/020503:INFO:CONSOLE(11)] ""[%cINFO%c] Scanning: Local Network for Airplay devices" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020503:INFO:CONSOLE(11)] ""[%cINFO%c] Scanning: Local Network for DLNA devices" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020503:INFO:CONSOLE(11)] ""[%cINFO%c] Scanning: /usr/bin" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020503:INFO:CONSOLE(11)] ""[%cINFO%c] Scanning: /usr/local/bin" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "cache_provider.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "cache_providerv2.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "favorites.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "opensubtitles.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "torrent_cache.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "trakttv.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "tvapi.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "tvshowtime.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(24)] ""loading local provider" "watchlist.js"", source: app://host/src/app/bootstrap.js (24)
>> [28749:0216/020503:INFO:CONSOLE(65)] ""loading npm" "butter-provider-ccc"", source: app://host/src/app/bootstrap.js (65)
>> [28749:0216/020503:INFO:CONSOLE(65)] ""added" "ccc" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020503:INFO:CONSOLE(65)] ""loading npm" "butter-provider-youtube"", source: app://host/src/app/bootstrap.js (65)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "youtube" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""loading npm" "butter-provider-vodo"", source: app://host/src/app/bootstrap.js (65)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "vodo" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""loading npm" "butter-provider-archive"", source: app://host/src/app/bootstrap.js (65)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "archive" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(11)] ""[%cINFO%c] Found External Player: mpv in /usr/bin" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020504:INFO:CONSOLE(11)] ""[%cINFO%c] External Players: scan finished" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020504:INFO:CONSOLE(11)] ""[%cINFO%c] Loading DB" "color: blue;" "color: black;"", source: app://host/src/app/app.js (11)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "cache_provider.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "cache_providerv2.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "Favorites" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "favorites.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "TorrentCache" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "torrent_cache.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "OpenSubtitles" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "opensubtitles.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "Trakttv" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "trakttv.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "TVShowTime" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "tvshowtime.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(21)] ""%c[%cERROR%c] Error: Cannot find module 'butter-provider-TVApi'" "color: black;" "color: red;" "color: black;" "Error: Cannot find module 'butter-provider-TVApi'\n    at Function.Module._resolveFilename (module.js:327:15)\n    at Function.Module._load (module.js:264:25)\n    at Module.require (module.js:356:17)\n    at require (module.js:375:17)\n    at window.require (\u003Canonymous\u003E:4:17)\n    at Object.getProvider [as get] (app://host/src/app/lib/providers/generic.js:30:60)\n    at app://host/src/app/lib/providers/watchlist.js:4:31\n    at app://host/src/app/lib/providers/watchlist.js:208:3"", source: app://host/src/app/app.js (21)
>> [28749:0216/020504:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'butter-provider-TVApi'", source: module.js (329)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "watchlist.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(65)] ""added" "TVApi" "to provider registry"", source: app://host/src/app/lib/providers/generic.js (65)
>> [28749:0216/020504:INFO:CONSOLE(35)] ""loaded" "tvapi.js"", source: app://host/src/app/bootstrap.js (35)
>> [28749:0216/020504:INFO:CONSOLE(21)] ""%c[%cERROR%c] Error starting up" "color: black;" "color: red;" "color: black;"", source: app://host/src/app/app.js (21)
>> [28749:0216/020504:INFO:CONSOLE(16)] ""[%cWARNING%c] Show Disclaimer" "color: orange;" "color: black;"", source: app://host/src/app/app.js (16)
>> [28809:0216/020902:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
>> [28809:0216/020902:WARNING:channel.cc(320)] RawChannel write error
>> Parent failed to complete crash dump.
```

**Comment by vankasteelj** [comment]
yep, it's broken. _looking at xaiki_

**Comment by vankasteelj** [comment]
this should be fixed now, is it?

**Comment by Grimmoire** [comment]
yep
