### ISSUE TITLE
Gulp run error

### ISSUE THREAD

**Issue by triedal** [butterproject/butter-desktop#384]
I have read the previous issues regarding gulp run errors but I am still unable to get the project up and running. After cloning the repo and running npm install, gulp run returns the following error:

```
Using v0.12.2
Create cache folder in /Users/tylerriedal/Documents/programming/butter-desktop/cache/0.12.2
Using cache for: osx32
[21:45:47] 'run' errored after 2.76 s
[21:45:47] TypeError: Cannot read property 'getRunnable' of undefined
    at NwBuilder.runApp (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/lib/index.js:585:28)
    at tryCatch1 (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/Users/tylerriedal/Documents/programming/butter-desktop/node_modules/nw-builder/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

If it is of any help I am using v5.7.1 of Node and 3.6.0 of NPM.

**Comment by streger** [comment]
Please wait a bit for a Pr to get merged:
https://github.com/butterproject/butter-desktop/pull/383

**Comment by triedal** [comment]
Will do! Thanks

**Comment by streger** [comment]
a bit was a bit exaggerated, you'll probably have to wait more that a bit... but you can pull that PR and test it out.

**Comment by vankasteelj** [comment]
merged 3 days after that, sorry didn't update the issue here. Can be closed.
