### ISSUE TITLE
Gulp run errored: spawn cache\0.12.2\win32/nw.exe

### ISSUE THREAD

**Issue by emiliopedrollo** [butterproject/butter-desktop#439]
### Description

Cannot run butter on Windows 10 after steps described [here](https://github.com/butterproject/butter-desktop/blob/master/docs/Build-Debug.md#windows).

I do have all the prerequisites. nodejs v4.6.0, npm 3.10.8 and Git 2.5.0.windows.1 

### Steps to Reproduce

1. `npm install -g gulp-cli`
2. `git clone https://github.com/butterproject/butter-desktop.git`
3. `npm install`
4. `gulp build`
5. `gulp run`

**Expected behavior:** Butter should run

**Actual behavior:** 'run' errored after 4.47 ms

```
B:\Users\Emilio\AppData\Local\Butter\butter-desktop>gulp run
[11:48:44] Using gulpfile B:\Users\Emilio\AppData\Local\Butter\butter-desktop\gulpfile.js
[11:48:44] Starting 'run'...
Running win32 from cache
win32 is not available in cache. Try running `gulp build` beforehand
[11:48:44] 'run' errored after 4.47 ms
[11:48:44] Error: spawn cache\0.12.2\win32/nw.exe ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
Butter exited with code -4058
```

Not sure if relevant but during `gulp build` i received status code 400 somewhere:
 
```
B:\Users\Emilio\AppData\Local\Butter\butter-desktop>gulp build
[11:47:39] Using gulpfile B:\Users\Emilio\AppData\Local\Butter\butter-desktop\gulpfile.js
[11:47:39] Starting 'build'...
[11:47:39] Starting 'injectgit'...
Branch: master
Commit: 8ca2ea8c
[11:47:39] Finished 'injectgit' after 90 ms
[11:47:39] Starting 'css'...
Stylus files compiled in B:\Users\Emilio\AppData\Local\Butter\butter-desktop\src\app\themes\
[11:47:42] Finished 'css' after 3.52 s
[11:47:42] Starting 'nwjs'...
Received status code 400: https://raw.githubusercontent.com/butterproject/nwjs-prebuilt/master/
[11:48:33] Finished 'nwjs' after 50 s
[11:48:33] Finished 'build' after 54 s
```

However it's exit code was 0.

### Technical details

- My OS is the Windows 10 with the Anniversary Update.
- I am running all commands as Administrator.

**Comment by vankasteelj** [comment]
It is the same problem as the last comment on #429 

fix : changing url to github.com, not raw.githubusercontent.com

**Comment by emiliopedrollo** [comment]
Didn't work. Same error.

**Comment by vankasteelj** [comment]
It's an easy fix but I didn't have time for it. 1sec

**Comment by vankasteelj** [comment]
Please `npm update` then `gulp build` again :)

**Comment by emiliopedrollo** [comment]
I have issued `npm update` and `gulp build` and the exact same error happened. However gulpfile was modified still. I will try a fresh install later today and will reply here with the results.
