### ISSUE TITLE
gulp run failed on Mac

### ISSUE THREAD

**Issue by lotux** [butterproject/butter-desktop#464]
### Description

gulp run fails on mac

when run gulp run in mac I get this error, I started by clean clone of the repo

```
laptop:butter-desktop user$ gulp run
[21:59:13] Using gulpfile ~/code/butter-desktop/gulpfile.js
[21:59:13] Starting 'run'...
Running osx32 from cache
[21:59:13] 'run' errored after 24 ms
[21:59:13] Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Promise (/Users/user/code/butter-desktop/gulpfile.js:153:23)
    at Gulp.gulp.task (/Users/user/code/butter-desktop/gulpfile.js:131:12)
    at module.exports (/Users/user/code/butter-desktop/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/user/code/butter-desktop/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/user/code/butter-desktop/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/user/code/butter-desktop/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
```
### Steps to Reproduce

1- git clone [repo address]
2- npm install
3- gulp build
4- gulp run
### Technical details

OS: MacOS El Capitan

**Comment by vankasteelj** [comment]
try `sudo chown -R $(whoami) ~/code/butter-desktop`

**Comment by josemigallas** [comment]
That didn't work for me (macOS Sierra)

**Comment by vankasteelj** [comment]
does this still happens?
