### ISSUE TITLE
en error in gulpfile.js 

### ISSUE THREAD

**Issue by dorukarda** [butterproject/butter-desktop#485]
I got an error every time when i try to build. 
```
/Users/doruk/butter-desktop/gulpfile.js:37
const parsePlatforms = () => {
                        ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
```

I am try exact order below. And i got error when trying to build.
npm install -g gulp-cli
npm install
gulp build

I'm using mac. 

Looking forward to your answers.

**Comment by vankasteelj** [comment]
Your node.js seems outdated, try `npm -v` and if it's below version 4, upgrade it

**Comment by dorukarda** [comment]
Thank you for your reply. 
I upgraded node. 
But now I'm getting this error while building. 

```
[17:07:52] Using gulpfile ~/popcorn/butter-desktop/gulpfile.js
[17:07:52] Starting 'build'...
[17:07:52] Starting 'injectgit'...
Branch: master
Commit: a7529a32
[17:07:53] Finished 'injectgit' after 815 ms
[17:07:53] Starting 'css'...
Stylus files compiled in /Users/doruk/popcorn/butter-desktop/src/app/themes/
[17:07:56] Finished 'css' after 3.01 s
[17:07:56] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! invalid: node-webkit-fdialogs@0.2.7 /Users/doruk/popcorn/butter-desktop/node_modules/node-webkit-fdialogs
npm ERR! invalid: colour@0.7.1 /Users/doruk/popcorn/butter-desktop/node_modules/nodecast-js/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/node_modules/ascli/node_modules/colour
npm ERR! invalid: optjs@3.2.2 /Users/doruk/popcorn/butter-desktop/node_modules/nodecast-js/node_modules/castv2-client/node_modules/castv2/node_modules/protobufjs/node_modules/ascli/node_modules/optjs

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
[17:07:59] Finished 'nwjs' after 3.31 s
[17:07:59] Finished 'build' after 7.13 s
```

Do you have any idea for this?

**Comment by xaiki** [comment]
remove your node_modules and start over.

**Comment by vankasteelj** [comment]
indeed, you used `npm install` with an outdated version of nodejs (probably npm v2 or something, it's v3 now)
