### ISSUE TITLE
Stuck at the loading when I run Butter

### ISSUE THREAD

**Issue by kidburglar** [butterproject/butter-desktop#538]
### Description

I stay stuck on the loading page after I start Butter.

### Steps to Reproduce

1. Clone the repository
2. Following the steps to build butter-desktop
3. gulp run

**Expected behavior:** [What you expect to happen]

See the application running after loading.

**Actual behavior:** [What actually happened]

It stay stuck at the loading page. I can click on a link that said "Loading stuck click here" but it only relaunch the application.

### Technical details
 
- Debian Jessie
- node: v7.2.1
- npm: 3.10.10
- Master branch
- I see an error about async and promise cannot used together (database.js:437)

**Comment by xaiki** [comment]
we're going to need a bit more to debug this like logs.
use args `--remote-debuggingport=9222` and open `http://localhost:9222`

**Comment by kidburglar** [comment]
I feel bad but I do ./build/Butter/linux64/Butter --remote-debuggingport=9222 but it not seem use localhost:9222

Maybe I have bad build something ?

**Comment by xaiki** [comment]
you need to find the nw binary and do ./nw . --remote... in the butter source directory

**Comment by xaiki** [comment]
anyway i think @vankasteelj could reproduce the issue i can't...

**Comment by kidburglar** [comment]
Mmm, I think I launch the good command but I cannot acces http://localhosst:9222
./cache/0.18.6-sdk/linux64/nw --remote-debuggingport=9222 .
I seem don't see any trafic for port 9222 with netstat -ntplou

**Comment by xaiki** [comment]
you have 2 's' in localhost

**Comment by kidburglar** [comment]
Oups, shame on me.
But seem http://localhost:9222/ or http://127.0.0.1:9222/ same issue.
I cannot help with F12 debug mode after I launch Butter directly ?

**Comment by xaiki** [comment]
sure, if you can post a trace of the error you're encountering.

**Comment by kidburglar** [comment]
[debug.txt](https://github.com/butterproject/butter-desktop/files/646657/debug.txt)

It's what I see in the console tab.

**Comment by btzr-io** [comment]
just got the same error: 
database.js:437 Error starting up Error: Options 'async' and 'promise' cannot be used together(…)(anonymous function) @ database.js:437

**Comment by xaiki** [comment]
what's in the '…' is what we're intrested in.

**Comment by xaiki** [comment]
(it's clickeable)

**Comment by btzr-io** [comment]
database.js:437 Error starting up Error: Options 'async' and 'promise' cannot be used together
    at self (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\memoizee\plain.js:18:9)
    at module.exports (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\memoizee\index.js:35:9)
    at Vodo.Provider (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\butter-provider\index.js:56:19)
    at new Vodo (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\butter-provider-vodo\index.js:18:13)
    at Promise_then_fulfilled (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\q\q.js:1369:30)
    at RawTask.call (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\asap\asap.js:40:19)
    at flush (C:\Users\baltazar\butter-desktop\build\Butter\win32\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ database.js:437
disclaimer.js:15 Show Disclaimerinitialize @ disclaimer.js:15

**Comment by kidburglar** [comment]
Faster than me ^^
I confirm I have the same.

**Comment by xaiki** [comment]
fixed by latest commit to butter-provider

**Comment by vankasteelj** [comment]
And it takes users for you to fix the issue I reported to you yesterday! (yeah, I know, I still havent reviewed you PR...)

**Comment by xaiki** [comment]
it actually takes a good trace to fix the issue <3

**Comment by vankasteelj** [comment]
you mean, this? that I sent you yesterday?

![firefox_2016-12-12_20-32-32](https://cloud.githubusercontent.com/assets/12599850/21113509/28d5a52c-c0aa-11e6-903b-b9b3f489e8cd.png)
