### ISSUE TITLE
gulp build fails due missing dependencies

### ISSUE THREAD

**Issue by juniorz** [butterproject/butter-desktop#625]
### Description

The project fails to build on mac os.

```
$ gulp build
...
[17:37:27] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: urijs@1.x.x, required by Butter@0.3.8-5a
npm ERR! missing: urijs@1.x.x, required by opensubtitles-api@3.5.0
npm ERR! peer dep missing: promise@>= 3.2.0, required by superagent-promise@0.2.0

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
...
```

### Steps to Reproduce

1. `rm -rf ~/.npm/`
2. `git clone https://github.com/butterproject/butter-desktop.git && cd butter-desktop`
3. `npm install -g gulp-cli`
4. `npm install`
5. `gulp build`
6. `gulp run`

### Possible fix

```
$ npm install "urijs@1.x.x" --save-dev
$ npm install "promise@>=3.2.0" --save-dev
$ npm install
```

**Comment by vankasteelj** [comment]
That's wierd, these deps should be included. Would you be using an old version of NPM by any chance ?

**Comment by juniorz** [comment]
```
$ node --version
v7.7.3
$ npm --version
4.1.2
```

I'm not sure how old is this. Is there any version restriction on the project? I could not find anything regarding npm/node version in the "Quickstart" section.

Thank you

**Comment by xaiki** [comment]
can you try with `yarn` ? `yarn install` instead of `npm install` i think i'd like to move to it for stability...
